# Generated by Django 3.1.4 on 2020-12-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='quad',
            field=models.CharField(choices=[('Q1', 'important and urgent'), ('Q2', 'important and not urgent'), ('Q3', 'not important and urgent'), ('Q4', 'not important and not urgent')], default='Q4', max_length=100),
        ),
    ]
