# Generated by Django 3.1.3 on 2020-11-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noting', '0002_note_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='deadline',
        ),
    ]
